sec_20_django_5/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
]

sec_20_django_5/sec_20_django_5/urls.py
from django.contrib import admin
from django.urls import include, path

from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),

    path('basic_app/', include('basic_app.urls')),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('special/', views.special, name='special')

]

from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sec_20_django_5/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

sec_20_django_5/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

sec_20_django_5/basic_app/views.py
from django.shortcuts import render
from django import forms

# login
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from basic_app.forms import UserForm, UserProfileInfoForm

# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def special(request):
    return HttpResponse("YOU ARE LOGGED IN")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False) # avoid collissions with user
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            
            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)
            raise forms.ValidationError('INVALID FORM')

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,
        'basic_app/register.html',
        {
            'registered': registered,
            'user_form': user_form,
            'profile_form': profile_form})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')

        else:
            print("FAILED LOGIN")
            return HttpResponse('INVALID LOGIN DETAILS')

    else:
        return render(request, 'basic_app/user_login.html')

sec_20_django_5/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{%url 'index'%}">Index</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link" href="{%url 'admin:index'%}">Admin</a>
              <a class="nav-link" href="{%url 'special'%}">Special</a>
              {% if user.is_authenticated %}
                <a class="nav-link" href="{%url 'basic_app:user_logout'%}">Logout</a>
              {% else %}
                <a class="nav-link active" aria-current="page" href="{%url 'basic_app:register'%}">Register</a>
                <a class="nav-link" href="{%url 'basic_app:user_login'%}">Login</a>
              {% endif %}

            </div>
          </div>
        </div>
    </nav>
    <div class="container py-4">
    <div class="p-5 mb-4 bg-light rounded-3">
    {% block body_block %}
    {% endblock body_block %}
    </div>
    </div>
</body>
</html>

sec_20_django_5/templates/basic_app/index.html
{%extends "basic_app/base.html" %}

{% block body_block %}
<h1 class="display-5 fw-bold">Django Level 5</h1>
{% if user.is_authenticated %}
    <p class="col-md-8 fs-4">Press the logout button!</p>
    <a href="{% url 'basic_app:user_logout'%}"><button class="btn btn-primary btn-lg" type="button">Logout</button></a>
    {% if user.userprofileinfo.profile_pic %}
        <p><img src="{{ user.userprofileinfo.profile_pic.url }}" alt=""></p>
    {% endif %}
{% else %}
    <p class="col-md-8 fs-4">Press register or login button!</p>
    <a href="{% url 'basic_app:register'%}"><button class="btn btn-primary btn-lg" type="button">Register</button></a>
    <a href="{% url 'basic_app:user_login'%}"><button class="btn btn-primary btn-lg" type="button">Login</button></a>
{% endif %}
{% endblock body_block %}

sec_20_django_5/templates/basic_app/register.html
{% extends 'basic_app/base.html' %}
{% load static %}

{% block body_block %}
{% if registered %}
    <h1>Thank you for creating an account, now login!</h1>
    <a href="{% url 'basic_app:user_login'%}"><button class="btn btn-primary btn-lg" type="button">Login</button></a>

{%else%}
    <h1>Register here!</h1>
    <h3>Fill out the form!</h3>

    <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit", class='btn btn-success', value='Register'>
    </form>
{% endif %}
{% endblock body_block %}

sec_20_django_5/templates/basic_app/user_login.html
{% extends 'basic_app/base.html' %}

{% block body_block %}
<h1>Please Login</h1>

<form action="{%url 'basic_app:user_login'%}" method='post'>
    {% csrf_token %}
    <label for="username">Username: </label>
    <input type="text", name="username" placeholder="Enter username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" value="Login" class='btn btn-success'>
</form>
{% endblock body_block %}